### ISSUE TITLE
Unable  to complete installation on Raspbian ARM

### ISSUE THREAD

**Issue by abenedetti1968** [ciromattia/kcc#634]
Unable to complete installation on Raspberry running Raspbian:

system hangs after following commands:

pi@raspberrypi:~/kcc $ sudo python3.8 -m pip install -r 'requirements.txt' 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyQt5>=5.6.0
  Using cached PyQt5-5.15.10.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... -

Many thanks.

**Comment by axu2** [comment]
Maybe merge in #523 first?

**Comment by abenedetti1968** [comment]
sorry not able to merge with #523.

do you know if there is a release working in raspbian ?

**Comment by axu2** [comment]
Why can't you merge?

Otherwise, maybe flatpak or appimage?
https://flathub.org/apps/details/io.github.ciromattia.kcc
![image](https://github.com/ciromattia/kcc/assets/20757319/96c45dca-cd15-473d-aef8-caf83d913212)
https://github.com/ciromattia/kcc/releases/tag/v5.6.4

**Comment by axu2** [comment]
@abenedetti1968 
https://github.com/ciromattia/kcc/wiki/Installation#linux-1

**Comment by abenedetti1968** [comment]
I'm very sorry ... this is what I obtain with AppImage following the guide:

pi@raspberrypi:~/kcc $ GDK_BACKEND=x11 ./kindleComicConverter-latest-x86_64.AppImage
bash: ./kindleComicConverter-latest-x86_64.AppImage: cannot execute binary file: Formato eseguibile non valido
pi@raspberrypi:~/kcc $ 

many thanks

**Comment by abenedetti1968** [comment]
![image](https://github.com/ciromattia/kcc/assets/51629168/1dc239b6-d0fd-4bb3-826e-c20d1ef173f7)

**Comment by abenedetti1968** [comment]
Trying with flatpak.
Could you please carify where is:
NOTE: Please put **kindlegen_linux_i386** to ~/.var/app/io.github.ciromattia.kcc/data/kindlegen

**Comment by axu2** [comment]
@abenedetti1968 Does the flatpak version run? 

Amazon no longer offers Kindlegen Linux, if you want to use it you'll need to find an archive of it somewhere.

**Comment by winstonma** [comment]
@axu2 The latest flatpak version doesn't work for me (#636 for more info). I have to install the previous version.

@abenedetti1968 I would suggest you could install the previous version to verify first
```bash
$ sudo flatpak update  --commit=199be7911bc102208f052391fbe3d1aad2749294195c6be440ba4ca17580cb5a io.github.ciromattia.kcc
$ flatpak run io.github.ciromattia.kcc
```

This command will run even `kindlegen` is not placed. As long as you can open KCC you can place `kindlegen` later on.

**Comment by abenedetti1968** [comment]
@winstonma this is what I obtain

pi@raspberrypi:~ $ flatpak install flathub io.github.ciromattia.kcc

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches?
error: Nothing matches io.github.ciromattia.kcc in remote flathub
pi@raspberrypi:~ $

**Comment by winstonma** [comment]
@abenedetti1968 I guess flatpak doesn't work for you

```
# Check the CPU architecture
$ uname -i
x86_64

# Check KCC flatpak info
$ flatpak remote-info flathub io.github.ciromattia.kcc
        ID: io.github.ciromattia.kcc
       Ref: app/io.github.ciromattia.kcc/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 12.9 MB
 Installed: 44.4 MB
   Runtime: org.kde.Platform/x86_64/5.15-23.08
       Sdk: org.kde.Sdk/x86_64/5.15-23.08

    Commit: 7b5fc1626564c3e4631c07f0b78ce2d263554e346f4936c30136ae5470e3ced3
    Parent: 199be7911bc102208f052391fbe3d1aad2749294195c6be440ba4ca17580cb5a
   Subject: Update v5.6.3.tar.gz to 5.6.4 (3a7442ea)
      Date: 2023-12-05 05:08:34 +0000
```

According to the flatpak output KCC only provide x86_64 version and R-Pi should be running arm64 so there is no match. Thus flatpak version should be dead end for you. Also I believe AppImage doesn't work for you too.

**Comment by winstonma** [comment]
@abenedetti1968 I just see your issue and find that you are doing the right thing. After searching on google it seems that installing PyQT5 on R-Pi using pip is a dead end ([link](https://www.pythonguis.com/installation/install-pyqt5-raspberry-pi/)).

It suggest that `sudo apt install python3-pyqt5`. After running the apt install command then you don't need to install PyQT5 via pip. That might solve your problem. Hope that helps.

**Comment by abenedetti1968** [comment]
@winstonma many thanks for your time. Already manually installed PyQT5. Followed the manual pip installation but I still have an error:

pi@raspberrypi:~/kcc $ pip3 install -r 'requirements.txt' 
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: PyQt5>=5.6.0 in /home/pi/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (5.15.10)
Requirement already satisfied: Pillow>=5.2.0 in /home/pi/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (10.1.0)
Requirement already satisfied: psutil>=5.0.0 in /home/pi/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (5.9.6)
Requirement already satisfied: python-slugify>=1.2.1 in /home/pi/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (8.0.1)
Requirement already satisfied: raven>=6.0.0 in /home/pi/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (6.10.0)
Collecting mozjpeg-lossless-optimization>=1.1.2 (from -r requirements.txt (line 7))
  Using cached mozjpeg-lossless-optimization-1.1.3.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting natsort>=8.4.0 (from natsort[fast]>=8.4.0->-r requirements.txt (line 8))
  Using cached https://www.piwheels.org/simple/natsort/natsort-8.4.0-py3-none-any.whl (38 kB)
Collecting distro (from -r requirements.txt (line 9))
  Using cached https://www.piwheels.org/simple/distro/distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: PyQt5-sip<13,>=12.13 in /home/pi/.local/lib/python3.8/site-packages (from PyQt5>=5.6.0->-r requirements.txt (line 1)) (12.13.0)
Requirement already satisfied: text-unidecode>=1.3 in /home/pi/.local/lib/python3.8/site-packages (from python-slugify>=1.2.1->-r requirements.txt (line 4)) (1.3)
Collecting cffi>=1.0.0 (from mozjpeg-lossless-optimization>=1.1.2->-r requirements.txt (line 7))
  Using cached cffi-1.16.0-cp38-cp38-linux_armv7l.whl
Collecting fastnumbers>=2.0.0 (from natsort[fast]>=8.4.0->-r requirements.txt (line 8))
  Using cached fastnumbers-5.1.0-cp38-cp38-linux_armv7l.whl
Collecting pycparser (from cffi>=1.0.0->mozjpeg-lossless-optimization>=1.1.2->-r requirements.txt (line 7))
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Building wheels for collected packages: mozjpeg-lossless-optimization
  Building wheel for mozjpeg-lossless-optimization (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  Building wheel for mozjpeg-lossless-optimization (pyproject.toml) did not run successfully.
  exit code: 1
  
  [13 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-cpython-38
  creating build/lib.linux-armv7l-cpython-38/mozjpeg_lossless_optimization
  copying mozjpeg_lossless_optimization/__init__.py -> build/lib.linux-armv7l-cpython-38/mozjpeg_lossless_optimization
  copying mozjpeg_lossless_optimization/mozjpeg_opti.py -> build/lib.linux-armv7l-cpython-38/mozjpeg_lossless_optimization
  copying mozjpeg_lossless_optimization/mozjpeg_opti_build.py -> build/lib.linux-armv7l-cpython-38/mozjpeg_lossless_optimization
  running build_ext
  generating cffi module 'build/temp.linux-armv7l-cpython-38/mozjpeg_lossless_optimization._mozjpeg_opti.c'
  creating build/temp.linux-armv7l-cpython-38
  error: [Errno 2] No such file or directory: 'cmake'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mozjpeg-lossless-optimization
Failed to build mozjpeg-lossless-optimization
ERROR: Could not build wheels for mozjpeg-lossless-optimization, which is required to install pyproject.toml-based projects
pi@raspberrypi:~/kcc $ 

Many thanks.

**Comment by winstonma** [comment]
@abenedetti1968 
In short, even KCC is working you still need arm64 version of kindlegen. So my advice is, your first step is to find the working kindlegen on R-Pi. Otherwise even if KCC is working you still need kindlegen to convert the file into kindle format.

For mozjpeg-lossless-optimization, You can check [mozjpeg-lossless-optimization files](https://pypi.org/project/mozjpeg-lossless-optimization/#files) that the module didn't have Linux arm64 build. They only provide arm64 build for MacOS or x86_64 for Linux. For this kind of case you could
* Build the mozjpeg-lossless-optimization package [from source](https://github.com/wanadev/mozjpeg-lossless-optimization#from-sources), I am not sure if that is 100% working or
* Try to comment out mozjpeg-lossless-optimization, install, and run KCC without mozjpeg-lossless-optimization. That package would only be used if you can skip using mozjpeg

**Comment by winstonma** [comment]
Yeah @darodi qemu would work but this is some advanced skill 🤔

It is not get flatpak install.

**Comment by pjft** [comment]
I'll bring this up again if possible, as I am being forced to remove all these apps from the laptop I've been using and would like to use the cli version on my Raspberry Pi 5, 64-bit OS.

The docker versions do not work at all - they always complain of missing dependencies, unfortunately, and I tried multiple versions. 

On the source version, I cannot install mozjpeg-lossless-optimization unfortunately. 

Any further thoughts or pointers, I'd be happy to explore.

**Comment by axu2** [comment]
@pjft Have you tried 5.6.5? What error are you getting with newer versions?

**Comment by axu2** [comment]
@pjft thanks for the info, I'm sure it will help someone in the future. 

I don't use docker, do you think you could look at the kcc dockerfiles and build it locally to see what's wrong?

**Comment by pjft** [comment]
Hm. I can try, but I never built any docker container. Is this mostly `git clone` and then `docker build` on the folder, or is there anything else I should do?

Happy to follow guidance. Let me know!

**Comment by pjft** [comment]
Ok, so I tried to do so. The first thing I noticed was that the .dockerignore file has the `Dockerfile` listed? Unsure if that's expected?

Either way, the current build with Dockerfile-base (I believe?) results in the current image with nothing installed, and saying it's missing the `packaging` module.

When I remove the Dockerfile from .dockerignore, and explicitly use the arm64 build instructions (I deleted the other ones) in my case it fails because it cannot resolve deb.debian.org to retrieve the required packages, and so it fails.

I tried several workarounds but was unsuccessful - everything from changing the Dockerfile to my own docker settings and everything in between.

I'm sure this is a configuration issue on my end that prevents it from accessing the internet, but since the only machine I have to run this is my production server, I'd rather not mess things up there, apologies.

Still, for you to try, you just do git clone and then docker build. 

Hope this helps.

**Comment by axu2** [comment]
@pjft I believe I've fixed the issue, can you try downloading the latest docker version?

**Comment by pjft** [comment]
@axu2 Thanks for reaching out - I'm happy to test as much as necessary, I imagine this can be helpful for others.

Alas, I wish I had better news. Unfortunately, still the same happens:

```
Traceback (most recent call last):
  File "/opt/kcc/kcc-c2e.py", line 28, in <module>
    from kindlecomicconverter.startup import startC2E
  File "/opt/kcc/kindlecomicconverter/startup.py", line 24, in <module>
    from .shared import dependencyCheck
  File "/opt/kcc/kindlecomicconverter/shared.py", line 25, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

However, something did change, as now we don't even have the `setuptools 65.5.0` there.

```
docker run --rm -it --entrypoint bash ghcr.io/ciromattia/kcc:6.2.0_linux_arm64
root@55893987405e:/app# pip list
Package Version
------- -------
pip     24.2
```

So, there's progress - at least the build is being changed. From reading your changes, they seem to be in the right direction, but did you check whether there's network connectivity during the build? In my case these were the errors I got when building using the ARM64 sections in Dockerfile-base:

```
=> [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 3.57kB                                                                                                                   0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)                                                                           0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 60)                                                                          0.0s
 => [internal] load metadata for docker.io/library/python:3.12-slim-bullseye                                                                             1.3s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 328B                                                                                                                        0.0s
 => [compile-arm64 1/3] FROM docker.io/library/python:3.12-slim-bullseye@sha256:913106afd670038aa28f9c9962ecde45cacaea346e909668cd9eb776b90f6bdd         0.3s
 => => resolve docker.io/library/python:3.12-slim-bullseye@sha256:913106afd670038aa28f9c9962ecde45cacaea346e909668cd9eb776b90f6bdd                       0.0s
 => => sha256:8775236a2b5fb5e3e1e0b9a97dd2d4be28e2016e5563dc6d136a1915a78fb76d 5.09kB / 5.09kB                                                           0.0s
 => => sha256:913106afd670038aa28f9c9962ecde45cacaea346e909668cd9eb776b90f6bdd 9.12kB / 9.12kB                                                           0.0s
 => => sha256:2eccc06020f799c6e616fc9866d1370c4e14b9aecb5f3e3da29a282fabe6eb7e 1.75kB / 1.75kB                                                           0.0s
 => [compile-arm64 2/3] RUN echo "I'm building for linux/arm64/"                                                                                         0.4s
 => ERROR [compile-arm64 3/3] RUN set -x &&     TEMP_PACKAGES=() &&     KEPT_PACKAGES=() &&     TEMP_PACKAGES+=(build-essential) &&     TEMP_PACKAGES+=  0.4s 
------                                                                                                                                                        
 > [compile-arm64 3/3] RUN set -x &&     TEMP_PACKAGES=() &&     KEPT_PACKAGES=() &&     TEMP_PACKAGES+=(build-essential) &&     TEMP_PACKAGES+=(cmake) &&     TEMP_PACKAGES+=(libfreetype6-dev) &&     TEMP_PACKAGES+=(libfontconfig1-dev) &&     TEMP_PACKAGES+=(libpng-dev) &&     TEMP_PACKAGES+=(libjpeg-dev) &&     TEMP_PACKAGES+=(libssl-dev) &&     TEMP_PACKAGES+=(libxft-dev) &&     TEMP_PACKAGES+=(make) &&     TEMP_PACKAGES+=(python3-dev) &&     TEMP_PACKAGES+=(python3-setuptools) &&     TEMP_PACKAGES+=(python3-wheel) &&     KEPT_PACKAGES+=(bash) &&     KEPT_PACKAGES+=(ca-certificates) &&     KEPT_PACKAGES+=(chrpath) &&     KEPT_PACKAGES+=(locales) &&     KEPT_PACKAGES+=(locales-all) &&     KEPT_PACKAGES+=(libfreetype6) &&     KEPT_PACKAGES+=(libfontconfig1) &&     KEPT_PACKAGES+=(p7zip-full) &&     KEPT_PACKAGES+=(python3) &&     KEPT_PACKAGES+=(python3-pip) &&     KEPT_PACKAGES+=(unrar-free) &&     DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get -yq upgrade &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends         ${KEPT_PACKAGES[@]}         ${TEMP_PACKAGES[@]}         &&     python -m pip install --upgrade pip &&     python -m venv /opt/venv &&     python -m pip install --upgrade pillow python-slugify psutil raven mozjpeg-lossless-optimization:
0.259 + TEMP_PACKAGES=()
0.259 + KEPT_PACKAGES=()
0.259 + TEMP_PACKAGES+=(build-essential)
0.259 + TEMP_PACKAGES+=(cmake)
0.260 + TEMP_PACKAGES+=(libfreetype6-dev)
0.260 + TEMP_PACKAGES+=(libfontconfig1-dev)
0.260 + TEMP_PACKAGES+=(libpng-dev)
0.260 + TEMP_PACKAGES+=(libjpeg-dev)
0.260 + TEMP_PACKAGES+=(libssl-dev)
0.260 + TEMP_PACKAGES+=(libxft-dev)
0.260 + TEMP_PACKAGES+=(make)
0.260 + TEMP_PACKAGES+=(python3-dev)
0.260 + TEMP_PACKAGES+=(python3-setuptools)
0.260 + TEMP_PACKAGES+=(python3-wheel)
0.260 + KEPT_PACKAGES+=(bash)
0.260 + KEPT_PACKAGES+=(ca-certificates)
0.260 + KEPT_PACKAGES+=(chrpath)
0.260 + KEPT_PACKAGES+=(locales)
0.260 + KEPT_PACKAGES+=(locales-all)
0.260 + KEPT_PACKAGES+=(libfreetype6)
0.260 + KEPT_PACKAGES+=(libfontconfig1)
0.260 + KEPT_PACKAGES+=(p7zip-full)
0.260 + KEPT_PACKAGES+=(python3)
0.260 + KEPT_PACKAGES+=(python3-pip)
0.260 + KEPT_PACKAGES+=(unrar-free)
0.260 + DEBIAN_FRONTEND=noninteractive
0.260 + apt-get update -y
0.282 Err:1 http://deb.debian.org/debian bullseye InRelease
0.282   Temporary failure resolving 'deb.debian.org'
0.282 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
0.282   Temporary failure resolving 'deb.debian.org'
0.282 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
0.282   Temporary failure resolving 'deb.debian.org'
0.285 Reading package lists...
0.293 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
0.293 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
0.293 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
0.293 W: Some index files failed to download. They have been ignored, or old ones used instead.
0.294 + apt-get -yq upgrade
0.301 Reading package lists...
0.308 Building dependency tree...
0.309 Reading state information...
0.311 Calculating upgrade...
0.315 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
0.316 + DEBIAN_FRONTEND=noninteractive
0.316 + apt-get install -y --no-install-recommends bash ca-certificates chrpath locales locales-all libfreetype6 libfontconfig1 p7zip-full python3 python3-pip unrar-free build-essential cmake libfreetype6-dev libfontconfig1-dev libpng-dev libjpeg-dev libssl-dev libxft-dev make python3-dev python3-setuptools python3-wheel
0.322 Reading package lists...
0.329 Building dependency tree...
0.330 Reading state information...
0.332 Package locales is not available, but is referred to by another package.
0.332 This may mean that the package is missing, has been obsoleted, or
0.332 is only available from another source
0.332 
0.332 Package locales-all is not available, but is referred to by another package.
0.332 This may mean that the package is missing, has been obsoleted, or
0.332 is only available from another source
0.332 
0.332 E: Unable to locate package chrpath
0.332 E: Package 'locales' has no installation candidate
0.332 E: Package 'locales-all' has no installation candidate
0.332 E: Unable to locate package libfreetype6
0.332 E: Unable to locate package libfontconfig1
0.332 E: Unable to locate package p7zip-full
0.332 E: Unable to locate package python3
0.332 E: Unable to locate package python3-pip
0.332 E: Unable to locate package unrar-free
0.332 E: Unable to locate package build-essential
0.332 E: Unable to locate package cmake
0.332 E: Unable to locate package libfreetype6-dev
0.332 E: Unable to locate package libfontconfig1-dev
0.332 E: Unable to locate package libpng-dev
0.332 E: Unable to locate package libjpeg-dev
0.332 E: Unable to locate package libssl-dev
0.332 E: Unable to locate package libxft-dev
0.332 E: Unable to locate package make
0.332 E: Unable to locate package python3-dev
0.332 E: Unable to locate package python3-setuptools
0.332 E: Unable to locate package python3-wheel
```

As I mentioned, however, at least with my build command it doesn't use the ARM64 section of the Dockerfile-base to install the dependencies. Maybe I have the wrong command on my end? And is the Dockerfile meant to be in .dockerignore?

Have a great evening!

**Comment by axu2** [comment]
@pjft Logs look fine to me:

![image](https://github.com/user-attachments/assets/16f9e436-6d40-4337-98ae-612e859a385b)


https://github.com/ciromattia/kcc/actions/runs/11087112362/job/30805452929

Have you run it like the wiki states?

https://github.com/ciromattia/kcc/wiki/Installation#docker

**Comment by pjft** [comment]
Well, that's cool - the logs indeed look great and it seems to suggest it's installing things correctly. 

It's past midnight here, but let me take a new look tomorrow then. I'm also not a docker expert, though I run a few containers on my server. There's certainly a non-negligible chance that this is an error on my end:)

Thanks for looking into this. I'll report back tomorrow.

**Comment by axu2** [comment]
@pjft made an additional change to match amd64 behavior, hopefully it works now on arm64

**Comment by pjft** [comment]
@axu2 yes, it finally does - well done! I can confirm that it now works. 

Thank you! You may at least now keep a reference that v6.2.0 works.

I added some lines on the installation instructions regarding accessing local and relative paths using the Docker version as it's harder than the command line.

Awesome work. You may close this now I believe.

**Comment by axu2** [comment]
Excellent, thanks for confirming. I'll do something similar for armv7.

@abenedetti1968

**Comment by axu2** [comment]
@pjft does the gui version work on docker arm64? kcc.py is the entry point.

**Comment by pjft** [comment]
@axu2 I apologize, but that I cannot comment on that part with a lot of confidence. My headless server runs a GUI-less version of the OS, I only have access to it via SSH and terminal. I'd have to defer to someone else, unfortunately, at least for the time being. 

I tried to bash into the container, navigate into /opt/kcc and run `python3 kcc.py`and I got the following error:

```
ERROR: PySide 6.5.1+ is not installed!
```

So I'm assuming it isn't working? I expected a Qt6 error or something related to not being able to access the display.
